---
repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        exclude: ^test/samples/
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
      - id: mypy
        args:
          - --strict
        additional_dependencies:
          - types-pyyaml
        exclude: ^test/
  - repo: https://github.com/pylint-dev/pylint
    rev: v3.0.2
    hooks:
      - id: pylint
        args:
          - --jobs=0
          - --disable=R0801
          - --disable=C0209
          - --disable=W0719 # broad-exception-raised (to activate back later)
        additional_dependencies:
          - pyyaml
        exclude: ^test/samples/
